{% set name = "riccati" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/riccati-{{ version }}.tar.gz
  sha256: 9c8fb6be786694038e929dd871b9f65cd4fff682731d5f1dbb4c9590d433605a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=40.6.0
    - wheel
    - setuptools-scm
    - pytest-runner
    - pip
    - versioneer
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - riccati
    - numpy
    - scipy
    - mpmath
  commands:
    - pip check
    - python -m pytest riccati/tests
  requires:
    - pip
    - numpy
    - scipy
    - mpmath
    - pytest
  source_files:
    - riccati/tests
    - riccati/tests/test_riccati.py

about:
  home: https://github.com/fruzsinaagocs/riccati
  summary: adaptive Riccati defect correction solver
  description: |
    riccati is a Python package for solving second order, linear, homogeneous
    ordinary differential equations with solutions that may become highly
    oscillatory over the solution interval. It implements the adaptive Riccati
    defect correction method described in https://arxiv.org/abs/2212.06924.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://riccati.readthedocs.io/
  dev_url: https://github.com/fruzsinaagocs/riccati

extra:
  recipe-maintainers:
    - fruzsinaagocs
